version: '3'

services:
  ros:
    container_name: ros_melodic_container
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    network_mode: "host"